### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by thetimeofblack** [gooofy/py-nltools#1] opened 2017-11-22 05:28 UTC
x86_64-linux-gnu-gcc: error: kaldiasr/nnet3.cpp: 没有那个文件或目录
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by gooofy** [comment] 2017-11-24 17:13
sounds like an issue with py-kaldi-asr (cython missing being most likely the cause), not py-nltools. Closing.

**Closed as completed by gooofy** 2017-11-24 17:13 UTC
